// Start of the script to generate HTML pages from markdown
(async () => {
  const fs = require('fs');
  const path = require('path');

  // Use dynamic import to load the 'marked' module (ESM support)
  const { marked } = await import('marked');  // Correctly access the 'marked' function from the 'marked' library

  const inputDir = path.join(__dirname, 'generated-articles'); // Directory where the markdown files are stored
  const outputDir = path.join(__dirname, 'pages'); // Directory where the HTML pages will be saved

  // Check if the output directory exists, create it if not
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir);
  }

  // Read all markdown files from the generated-articles directory
  fs.readdirSync(inputDir).forEach(file => {
    const filePath = path.join(inputDir, file);  // Full path to the current markdown file
    const fileName = path.basename(file, '.md'); // Extract the file name without the .md extension

    // Skip non-markdown files
    if (path.extname(file) !== '.md') return;

    // Read the content of the markdown file and convert it to HTML
    const markdownContent = fs.readFileSync(filePath, 'utf-8');
    const htmlContent = marked(markdownContent);  // Convert Markdown to HTML using the 'marked' function

    // Create a simple HTML template to wrap the converted content
    const htmlPage = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Article: ${fileName}</title>
        <link rel="stylesheet" href="styles.css"> <!-- Optional: Link to a CSS file for styling -->
    </head>
    <body>
        <header>
            <h1>Best Flights to ${fileName}</h1>
        </header>
        <main>
            ${htmlContent}  <!-- Insert the Markdown content here as HTML -->
        </main>
        <footer>
            <p>Generated by GitHub Actions - Skyscanner Articles</p>
        </footer>
    </body>
    </html>
    `;

    // Write the generated HTML content to the output directory
    const outputFilePath = path.join(outputDir, `${fileName}.html`);
    fs.writeFileSync(outputFilePath, htmlPage); // Write the HTML content to the file system

    console.log(`Generated HTML page: ${outputFilePath}`); // Log the generated page for debugging
  });
})();
