const fs = require('fs');
const path = require('path');
const marked = require('marked');  // Markdown to HTML converter

// Input and Output directories
const inputDir = path.join(__dirname, 'generated-articles');
const outputDir = path.join(__dirname, 'pages');

// Check if output directory exists, create it if not
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir);
}

// Read all markdown files from the generated-articles directory
fs.readdirSync(inputDir).forEach(file => {
    const filePath = path.join(inputDir, file);
    const fileName = path.basename(file, '.md');  // Extract file name without extension

    // Skip non-markdown files
    if (path.extname(file) !== '.md') return;

    // Read and convert the markdown file to HTML
    const markdownContent = fs.readFileSync(filePath, 'utf-8');
    const htmlContent = marked(markdownContent);  // Convert Markdown to HTML

    // Create a simple HTML template
    const htmlPage = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Article: ${fileName}</title>
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>
        <header>
            <h1>Best Flights to ${fileName}</h1>
        </header>
        <main>
            ${htmlContent}  <!-- Insert the Markdown content here -->
        </main>
        <footer>
            <p>Generated by GitHub Actions - Skyscanner Articles</p>
        </footer>
    </body>
    </html>
    `;

    // Write the HTML content to the output directory
    const outputFilePath = path.join(outputDir, `${fileName}.html`);
    fs.writeFileSync(outputFilePath, htmlPage);

    console.log(`Generated HTML page: ${outputFilePath}`);
});
